Monitoring 1
Otus-DevOps-2022-05/r2d2k_microservices pull request #5
Opened 2022-11-08 20:28 UTC by r2d2k

# Выполнено ДЗ № 17

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Подробное описание в README.md

## Как запустить проект:
 - Подробное описание в README.md

## Как проверить работоспособность:
 - Подробное описание в README.md

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2022-11-10 17:16 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
К сожалению не хватает некоторых файлов, рекомендую свериться с результатами тестов
ДЗ возвращаю на доработку

2022-11-10 18:20 UTC, r2d2k commented
Как вы мне сказали в прошлый раз: 
Тут "привет" особенностям GA
Иногда такое бывает, когда вы параллельно ведете работу в другой ветке

Проверьте результаты тестов с меткой monitoring-1, там всё чисто.
Ошибка снова пришла из logging-1.

2022-11-12 13:20 UTC, r2d2k commented
Я понял, как чинить проверки. Достаточно запустить её ещё раз, после выполнения следующего задания.

2022-11-20 17:40 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-11-20 17:44 UTC, merged